### ISSUE TITLE
 Unexpected end of input

### ISSUE THREAD

**Issue by iconio** [frontendista/astro-html-minify#2]
Hi! I'm trying to use this integration but when I'm building the project, I get this error:

```
 optimizing html 
 error   Unexpected end of input
SyntaxError: Unexpected end of input
    at Object.$c8628c1b558bdb05$export$d8b8918b6bb82ee [as minifyCSS] (file:///Users/wd/project/website/v2/node_modules/@frontendista/astro-html-minify/lib/index.esm.js:80:31)
    at cleanAttributeValue (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:322:20)
    at normalizeAttr (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:562:23)
    at Object.start (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:1072:34)
    at handleStartTag (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlparser.js:383:23)
    at HTMLParser.parse (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlparser.js:190:19)
    at async minifyHTML (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:1276:3)
    at async createSortFns (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:817:14)
    at async minifyHTML (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:947:5)
    at async minify (file:///Users/wd/project/website/v2/node_modules/html-minifier-terser/src/htmlminifier.js:1361:18)
```

I'm running Astro 2.1.2

Thanks

**Comment by susickypavel** [comment]
Hi,

It's hard to tell what the issue might be without reproduction. Empty project with Astro 2 builds fine. Could you provide minimal repro?

You can try to use [astro-compress](https://www.npmjs.com/package/astro-compress) instead, which is more robust and optimizes other resources.
